mv  Sc-Sc-C-O-O		  /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-C-H-H           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-C-F-F           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-C-Cl-Cl         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-C-Br-Br         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-C-I-I           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-C-S-S           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-C-Se-Se         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-C-Te-Te         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-C-OH-OH         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-C-ONa-ONa       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-C-OLi-OLi       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-C-OK-OK         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-C-OCN-OCN       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-C-OCHO-OCHO     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-C-OCH3-OCH3     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-C-O-O             /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-C-H-H             /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-C-F-F             /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-C-Cl-Cl           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-C-Br-Br           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-C-I-I             /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-C-S-S             /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-C-Se-Se           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-C-Te-Te           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-C-OH-OH           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-C-ONa-ONa         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-C-OLi-OLi         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-C-OK-OK           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-C-OCN-OCN         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-C-OCHO-OCHO       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-C-OCH3-OCH3       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-C-O-O           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-C-H-H           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-C-F-F           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-C-Cl-Cl         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-C-Br-Br         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-C-I-I           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-C-S-S           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-C-Se-Se         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-C-Te-Te         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-C-OH-OH         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-C-ONa-ONa       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-C-OLi-OLi       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-C-OK-OK         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-C-OCN-OCN       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-C-OCHO-OCHO     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-C-OCH3-OCH3     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-C-O-O           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-C-H-H           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-C-F-F           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-C-Cl-Cl         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-C-Br-Br         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-C-I-I           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-C-S-S           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-C-Se-Se         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-C-Te-Te         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-C-OH-OH         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-C-ONa-ONa       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-C-OLi-OLi       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-C-OK-OK         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-C-OCN-OCN       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-C-OCHO-OCHO     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-C-OCH3-OCH3     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-C-O-O           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-C-H-H           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-C-F-F           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-C-Cl-Cl         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-C-Br-Br         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-C-I-I           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-C-S-S           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-C-Se-Se         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-C-Te-Te         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-C-OH-OH         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-C-ONa-ONa       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-C-OLi-OLi       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-C-OK-OK         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-C-OCN-OCN       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-C-OCHO-OCHO     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-C-OCH3-OCH3     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-C-O-O             /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-C-H-H             /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-C-F-F             /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-C-Cl-Cl           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-C-Br-Br           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-C-I-I             /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-C-S-S             /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-C-Se-Se           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-C-Te-Te           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-C-OH-OH           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-C-ONa-ONa         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-C-OLi-OLi         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-C-OK-OK           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-C-OCN-OCN         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-C-OCHO-OCHO       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-C-OCH3-OCH3       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-C-O-O           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-C-H-H           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-C-F-F           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-C-Cl-Cl         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-C-Br-Br         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-C-I-I           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-C-S-S           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-C-Se-Se         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-C-Te-Te         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-C-OH-OH         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-C-ONa-ONa       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-C-OLi-OLi       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-C-OK-OK         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-C-OCN-OCN       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-C-OCHO-OCHO     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-C-OCH3-OCH3     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-C-O-O           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-C-H-H           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-C-F-F           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-C-Cl-Cl         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-C-Br-Br         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-C-I-I           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-C-S-S           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-C-Se-Se         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-C-Te-Te         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-C-OH-OH         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-C-ONa-ONa       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-C-OLi-OLi       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-C-OK-OK         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-C-OCN-OCN       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-C-OCHO-OCHO     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-C-OCH3-OCH3     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-C-O-O           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-C-H-H           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-C-F-F           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-C-Cl-Cl         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-C-Br-Br         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-C-I-I           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-C-S-S           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-C-Se-Se         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-C-Te-Te         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-C-OH-OH         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-C-ONa-ONa       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-C-OLi-OLi       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-C-OK-OK         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-C-OCN-OCN       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-C-OCHO-OCHO     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-C-OCH3-OCH3     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-C-O-O           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-C-H-H           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-C-F-F           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-C-Cl-Cl         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-C-Br-Br         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-C-I-I           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-C-S-S           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-C-Se-Se         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-C-Te-Te         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-C-OH-OH         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-C-ONa-ONa       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-C-OLi-OLi       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-C-OK-OK         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-C-OCN-OCN       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-C-OCHO-OCHO     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-C-OCH3-OCH3     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-C-O-O             /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-C-H-H             /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-C-F-F             /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-C-Cl-Cl           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-C-Br-Br           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-C-I-I             /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-C-S-S             /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-C-Se-Se           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-C-Te-Te           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-C-OH-OH           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-C-ONa-ONa         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-C-OLi-OLi         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-C-OK-OK           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-C-OCN-OCN         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-C-OCHO-OCHO       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-C-OCH3-OCH3       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-N-O-O           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-N-H-H           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-N-F-F           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-N-Cl-Cl         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-N-Br-Br         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-N-I-I           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-N-S-S           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-N-Se-Se         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-N-Te-Te         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-N-OH-OH         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-N-ONa-ONa       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-N-OLi-OLi       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-N-OK-OK         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-N-OCN-OCN       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-N-OCHO-OCHO     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Sc-Sc-N-OCH3-OCH3     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-N-O-O             /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-N-H-H             /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-N-F-F             /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-N-Cl-Cl           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-N-Br-Br           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-N-I-I             /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-N-S-S             /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-N-Se-Se           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-N-Te-Te           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-N-OH-OH           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-N-ONa-ONa         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-N-OLi-OLi         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-N-OK-OK           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-N-OCN-OCN         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-N-OCHO-OCHO       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Y-Y-N-OCH3-OCH3       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-N-O-O           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-N-H-H           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-N-F-F           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-N-Cl-Cl         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-N-Br-Br         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-N-I-I           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-N-S-S           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-N-Se-Se         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-N-Te-Te         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-N-OH-OH         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-N-ONa-ONa       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-N-OLi-OLi       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-N-OK-OK         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-N-OCN-OCN       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-N-OCHO-OCHO     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ti-Ti-N-OCH3-OCH3     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-N-O-O           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-N-H-H           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-N-F-F           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-N-Cl-Cl         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-N-Br-Br         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-N-I-I           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-N-S-S           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-N-Se-Se         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-N-Te-Te         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-N-OH-OH         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-N-ONa-ONa       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-N-OLi-OLi       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-N-OK-OK         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-N-OCN-OCN       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-N-OCHO-OCHO     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Zr-Zr-N-OCH3-OCH3     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-N-O-O           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-N-H-H           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-N-F-F           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-N-Cl-Cl         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-N-Br-Br         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-N-I-I           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-N-S-S           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-N-Se-Se         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-N-Te-Te         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-N-OH-OH         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-N-ONa-ONa       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-N-OLi-OLi       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-N-OK-OK         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-N-OCN-OCN       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-N-OCHO-OCHO     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Hf-Hf-N-OCH3-OCH3     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-N-O-O             /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-N-H-H             /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-N-F-F             /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-N-Cl-Cl           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-N-Br-Br           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-N-I-I             /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-N-S-S             /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-N-Se-Se           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-N-Te-Te           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-N-OH-OH           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-N-ONa-ONa         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-N-OLi-OLi         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-N-OK-OK           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-N-OCN-OCN         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-N-OCHO-OCHO       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  V-V-N-OCH3-OCH3       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-N-O-O           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-N-H-H           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-N-F-F           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-N-Cl-Cl         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-N-Br-Br         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-N-I-I           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-N-S-S           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-N-Se-Se         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-N-Te-Te         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-N-OH-OH         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-N-ONa-ONa       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-N-OLi-OLi       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-N-OK-OK         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-N-OCN-OCN       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-N-OCHO-OCHO     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Nb-Nb-N-OCH3-OCH3     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-N-O-O           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-N-H-H           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-N-F-F           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-N-Cl-Cl         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-N-Br-Br         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-N-I-I           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-N-S-S           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-N-Se-Se         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-N-Te-Te         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-N-OH-OH         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-N-ONa-ONa       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-N-OLi-OLi       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-N-OK-OK         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-N-OCN-OCN       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-N-OCHO-OCHO     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Ta-Ta-N-OCH3-OCH3     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-N-O-O           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-N-H-H           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-N-F-F           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-N-Cl-Cl         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-N-Br-Br         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-N-I-I           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-N-S-S           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-N-Se-Se         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-N-Te-Te         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-N-OH-OH         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-N-ONa-ONa       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-N-OLi-OLi       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-N-OK-OK         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-N-OCN-OCN       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-N-OCHO-OCHO     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Cr-Cr-N-OCH3-OCH3     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-N-O-O           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-N-H-H           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-N-F-F           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-N-Cl-Cl         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-N-Br-Br         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-N-I-I           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-N-S-S           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-N-Se-Se         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-N-Te-Te         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-N-OH-OH         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-N-ONa-ONa       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-N-OLi-OLi       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-N-OK-OK         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-N-OCN-OCN       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-N-OCHO-OCHO     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  Mo-Mo-N-OCH3-OCH3     /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-N-O-O             /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-N-H-H             /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-N-F-F             /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-N-Cl-Cl           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-N-Br-Br           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-N-I-I             /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-N-S-S             /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-N-Se-Se           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-N-Te-Te           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-N-OH-OH           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-N-ONa-ONa         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-N-OLi-OLi         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-N-OK-OK           /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-N-OCN-OCN         /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-N-OCHO-OCHO       /home/arun/work/ML/2.CB-31000-geom/MMXTT
mv  W-W-N-OCH3-OCH3       /home/arun/work/ML/2.CB-31000-geom/MMXTT
